[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[INFO] (k) This package is up to date.
[INFO] (k-combinat-for-sage) This package is up to date.
[INFO] (k-index-calculator) This package is up to date.
[INFO] (k-load) This package is up to date.
[INFO] (k-means-plus-plus) This package is up to date.
[INFO] (k-sequencing) This package is up to date.
[INFO] (k2-compose) This package is up to date.
[INFO] (k2-pix) This package is up to date.
[INFO] (k2catalogue) This package is up to date.
[INFO] (k2d) This package is up to date.
[INFO] (k2ephem) This package is up to date.
[INFO] (k2flix) This package is up to date.
[INFO] (k2fov) This package is up to date.
[INFO] (k2k) This package is up to date.
[INFO] (k2mosaic) This package is up to date.
[INFO] (k2pix) This package is up to date.
[INFO] (k2plr) This package is up to date.
[INFO] (k3d) This package is up to date.
[ERROR] (k5dstatus) This package does not have downloadable releases.
[INFO] (k5test) This package is up to date.
[INFO] (k5viz) This package is up to date.
[INFO] (k7) This package is up to date.
[INFO] (k8env) This package is up to date.
[INFO] (k8s) This package is up to date.
[INFO] (k8s-build-maps) This package is up to date.
[INFO] (k8s-google-authenticator) This package is up to date.
[INFO] (k8s-helper) This package is up to date.
[INFO] (k8sdc) This package is up to date.
[INFO] (k8senv) This package is up to date.
[INFO] (k8svag) This package is up to date.
[INFO] (ka-lite) This package is up to date.
[INFO] (ka-lite-gtk) This package is up to date.
[INFO] (ka-lite-static) This package is up to date.
[INFO] (ka-lite-zim) This package is up to date.
[INFO] (ka-nester) This package is up to date.
[ERROR] (kaa) Could not extract data from this package. See below for details.
"http://zephyrfalcon.org/download/kaa-0.9.zip" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

[INFO] (kaa-base) This package is up to date.
[INFO] (kaa-candy) This package is up to date.
[INFO] (kaa-display) This package is up to date.
[INFO] (kaa-imlib2) This package is up to date.
[INFO] (kaa-metadata) This package is up to date.
[INFO] (kaaboom) This package is up to date.
[INFO] (kaadbg) This package is up to date.
[INFO] (kaaedit) This package is up to date.
[INFO] (kaathletelist) This package is up to date.
[INFO] (kabaret) This package is up to date.
[INFO] (kabaret-naming) This package is up to date.
[INFO] (kabob) This package is up to date.
[INFO] (kaboom) This package is up to date.
[INFO] (kabuki) This package is up to date.
[INFO] (kabutopy) This package is up to date.
[INFO] (kache) This package is up to date.
[INFO] (kaching) This package is up to date.
[ERROR] (kacho) This package does not have downloadable releases.
[INFO] (kacors485) This package is up to date.
[INFO] (kaczmarz) This package is up to date.
[INFO] (kad-py) This package is up to date.
[INFO] (kadabra) This package is up to date.
[INFO] (kadal) This package is up to date.
[INFO] (kade) This package is up to date.
[INFO] (kademlia) This package is up to date.
[INFO] (kadmin) This package is up to date.
[INFO] (kadmin-local) This package is up to date.
[INFO] (kadmos) This package is up to date.
[INFO] (kadot) This package is up to date.
[INFO] (kael) This package is up to date.
[INFO] (kaeru-parser) This package is up to date.
[INFO] (kaeruprofiler) This package is up to date.
[INFO] (kafe) This package is up to date.
[INFO] (kafka) This package is up to date.
[INFO] (kafka-arrow-py) This package is up to date.
[INFO] (kafka-bus-python) This package is up to date.
[INFO] (kafka-cffi) This package is up to date.
[INFO] (kafka-connect-python) This package is up to date.
[INFO] (kafka-connector) This package is up to date.
[INFO] (kafka-dev-tools) This package is up to date.
[INFO] (kafka-helper) This package is up to date.
[INFO] (kafka-influxdb) This package is up to date.
[INFO] (kafka-log-handler) This package is up to date.
[INFO] (kafka-logger) This package is up to date.
[INFO] (kafka-python) This package is up to date.
[INFO] (kafka-quixey) This package is up to date.
[INFO] (kafka-replayer) This package is up to date.
[INFO] (kafka-rest) This package is up to date.
[INFO] (kafka-rest-client) This package is up to date.
[INFO] (kafka-scanner) This package is up to date.
[INFO] (kafka-store) This package is up to date.
[INFO] (kafka-tfrx) This package is up to date.
[INFO] (kafka-tools) This package is up to date.
[INFO] (kafka-utils) This package is up to date.
[INFO] (kafkabridgeclient) This package is up to date.
[INFO] (kafkacli) This package is up to date.
[INFO] (kafkaesque) This package is up to date.
[INFO] (kafkaka) This package is up to date.
[INFO] (kafkapython) This package is up to date.
[INFO] (kafkatos3) This package is up to date.
[INFO] (kafnafparserpy) This package is up to date.
[INFO] (kaftools) This package is up to date.
[INFO] (kafx) This package is up to date.
[INFO] (kage) This package is up to date.
[INFO] (kaggle) This package is up to date.
[ERROR] (kaggle-buddy) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kaggle-cli) This package is up to date.
[INFO] (kaggle-data) This package is up to date.
[INFO] (kaggle-metrics) This package is up to date.
[INFO] (kaggle-tools) This package is up to date.
[INFO] (kaggler) This package is up to date.
[INFO] (kagin) This package is up to date.
[INFO] (kagiso-django-auth) This package is up to date.
[INFO] (kagiso-flake8) This package is up to date.
[INFO] (kagiso-image) This package is up to date.
[INFO] (kagiso-search) This package is up to date.
[INFO] (kagiso-sitemap) This package is up to date.
[INFO] (kagiso-smart-404) This package is up to date.
[INFO] (kagiso-wagtail-slack) This package is up to date.
[INFO] (kahanit) This package is up to date.
[INFO] (kahgean) This package is up to date.
[INFO] (kahipwrapper) This package is up to date.
[INFO] (kahootbot) This package is up to date.
[INFO] (kai) This package is up to date.
[INFO] (kai-template) This package is up to date.
[ERROR] (kaia) This package does not have downloadable releases.
[INFO] (kaic-analysis) This package is up to date.
[INFO] (kaichu) This package is up to date.
[INFO] (kaidoku) This package is up to date.
[INFO] (kaif) This package is up to date.
[INFO] (kaiju) This package is up to date.
[INFO] (kaikobittrex) This package is up to date.
[INFO] (kailash) This package is up to date.
[INFO] (kaipy) This package is up to date.
[INFO] (kaira) This package is up to date.
[INFO] (kaircs) This package is up to date.
[INFO] (kairios) This package is up to date.
[INFO] (kairos) This package is up to date.
[INFO] (kaiso) This package is up to date.
[INFO] (kaitaistruct) This package is up to date.
[INFO] (kaizen) This package is up to date.
[INFO] (kajiki) This package is up to date.
[ERROR] (kakao) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (kakaoa) This package does not have downloadable releases.
[INFO] (kakaobot) This package is up to date.
[INFO] (kakaoplus) This package is up to date.
[INFO] (kakaoryan) This package is up to date.
[ERROR] (kakaos) This package does not have downloadable releases.
[ERROR] (kakaotalk) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kakasi-utils) This package is up to date.
[INFO] (kaki) This package is up to date.
[INFO] (kako) This package is up to date.
[INFO] (kakuro) This package is up to date.
[INFO] (kalamine) This package is up to date.
[INFO] (kalapy) This package is up to date.
[INFO] (kale) This package is up to date.
[INFO] (kaleo) This package is up to date.
[INFO] (kales) This package is up to date.
[ERROR] (kali) This package does not have downloadable releases.
[INFO] (kalibrate) This package is up to date.
[INFO] (kalibro-client) This package is up to date.
[INFO] (kalipto) This package is up to date.
[INFO] (kalkulacka) This package is up to date.
[INFO] (kallankallan-nester) This package is up to date.
[INFO] (kallikrein) This package is up to date.
[INFO] (kalliope) This package is up to date.
[INFO] (kallithea) This package is up to date.
[INFO] (kallithea-auth-container-internal) This package is up to date.
[INFO] (kallithea-auth-google) This package is up to date.
[INFO] (kalman) This package is up to date.
[INFO] (kalpa) This package is up to date.
[INFO] (kalsimplenester) This package is up to date.
[INFO] (kalturaapiclient) This package is up to date.
[INFO] (kalturaottapiclient) This package is up to date.
[INFO] (kama) This package is up to date.
[INFO] (kamaelia) This package is up to date.
[INFO] (kamaki) This package is up to date.
[INFO] (kambo) This package is up to date.
[INFO] (kamcilifoo) This package is up to date.
[INFO] (kamene) This package is up to date.
[INFO] (kamer) This package is up to date.
[INFO] (kameris) This package is up to date.
[INFO] (kameris-formats) This package is up to date.
[INFO] (kamidana) This package is up to date.
[INFO] (kamikaze) This package is up to date.
[INFO] (kamma) This package is up to date.
[INFO] (kamnanditestfile) This package is up to date.
[INFO] (kamo) This package is up to date.
[INFO] (kamonohashi-cli) This package is up to date.
[INFO] (kamonohashi-sdk) This package is up to date.
[ERROR] (kampuchea) This package does not have downloadable releases.
[INFO] (kamy) This package is up to date.
[INFO] (kan) This package is up to date.
[INFO] (kan-ml) This package is up to date.
[ERROR] (kana) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kanaconv) This package is up to date.
[INFO] (kanagata) This package is up to date.
[INFO] (kanban-simulator) This package is up to date.
[INFO] (kanboard) This package is up to date.
[INFO] (kanboard-cli) This package is up to date.
[INFO] (kanboard-gitlab) This package is up to date.
[INFO] (kanc) This package is up to date.
[INFO] (kandilli) This package is up to date.
[INFO] (kando) This package is up to date.
[INFO] (kandu) This package is up to date.
[INFO] (kaneda) This package is up to date.
[INFO] (kanedama) This package is up to date.
[INFO] (kangkangpy-nester) This package is up to date.
[INFO] (kangrouter-py) This package is up to date.
[INFO] (kanichart) This package is up to date.
[INFO] (kanika) This package is up to date.
[INFO] (kanit) This package is up to date.
[INFO] (kanji-to-romaji) This package is up to date.
[INFO] (kanjinetworks) This package is up to date.
[INFO] (kankube) This package is up to date.
[INFO] (kanone) This package is up to date.
[INFO] (kanpy) This package is up to date.
[INFO] (kanren) This package is up to date.
[INFO] (kanripo) This package is up to date.
[ERROR] (kansas) This package does not have downloadable releases.
[INFO] (kansha) This package is up to date.
[INFO] (kant) This package is up to date.
[INFO] (kantag) This package is up to date.
[INFO] (kanten) This package is up to date.
[INFO] (kantonzugpdf) This package is up to date.
[ERROR] (kaolibrary) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (kaoru) This package is up to date.
[INFO] (kaos) This package is up to date.
[INFO] (kaoz) This package is up to date.
[ERROR] (kapellmeister-ansible) This package does not have downloadable releases.
[INFO] (kapitan) This package is up to date.
[INFO] (kaplot) This package is up to date.
[INFO] (kapok) This package is up to date.
[INFO] (kapp) This package is up to date.
[INFO] (kappa) This package is up to date.
[INFO] (kappacuda) This package is up to date.
[INFO] (kappy) This package is up to date.
[INFO] (kapre) This package is up to date.
[ERROR] (kapri) Could not extract data from this package. See below for details.
"https://github.com/Oscailt/kapri.git/tarball/master" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kapsel) This package is up to date.
[INFO] (kaptan) This package is up to date.
[INFO] (kapteyn) This package is up to date.
[INFO] (kaptl) This package is up to date.
[INFO] (kaputt) This package is up to date.
[INFO] (karaage) This package is up to date.
[INFO] (karaage-cluster-tools) This package is up to date.
[INFO] (karabo-bridge) This package is up to date.
[INFO] (karabo-data) This package is up to date.
[ERROR] (karait) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (karakuri) This package is up to date.
[INFO] (karamel) This package is up to date.
[INFO] (karatsuba) This package is up to date.
[INFO] (karbor) This package is up to date.
[INFO] (karbor-dashboard) This package is up to date.
[INFO] (kardus) This package is up to date.
[INFO] (karel) This package is up to date.
[INFO] (karellen-geventws) This package is up to date.
[INFO] (karellen-kombu-ext) This package is up to date.
[INFO] (karellen-pyb-plugin) This package is up to date.
[INFO] (karellen-sqlite) This package is up to date.
[INFO] (karellen-stack-core) This package is up to date.
[INFO] (karellen-testing) This package is up to date.
[ERROR] (karesansui) This package does not have downloadable releases.
[INFO] (kargo) This package is up to date.
[ERROR] (karim-distribution) This package does not have downloadable releases.
[INFO] (karix) This package is up to date.
[INFO] (karld) This package is up to date.
[INFO] (karlooper) This package is up to date.
[ERROR] (karma) This package does not have downloadable releases.
[INFO] (karma-sphinx-theme) This package is up to date.
[INFO] (karmadbg) This package is up to date.
[INFO] (karman) This package is up to date.
[INFO] (karmapi) This package is up to date.
[INFO] (karnickel) This package is up to date.
[ERROR] (karrigell) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://code.google.com/p/karrigell/downloads/detail?name=Karrigell-4.3.9.gz&can=2&q="
[INFO] (karta) This package is up to date.
[INFO] (kartoffel) This package is up to date.
[ERROR] (kartograph) This package does not have downloadable releases.
[INFO] (karton) This package is up to date.
[INFO] (kartskrape) This package is up to date.
[INFO] (karura) This package is up to date.
[INFO] (kas) This package is up to date.
[INFO] (kasami) This package is up to date.
[INFO] (kasane) This package is up to date.
[INFO] (kash) This package is up to date.
[INFO] (kaskara) This package is up to date.
[INFO] (kaskuspy) This package is up to date.
[INFO] (kassis-numbering) This package is up to date.
[INFO] (kastore) This package is up to date.
[INFO] (kat) This package is up to date.
[INFO] (kata-scrape) This package is up to date.
[INFO] (katabankocr) This package is up to date.
[INFO] (katagami) This package is up to date.
[INFO] (katal) This package is up to date.
[ERROR] (katalog) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (katana) This package is up to date.
[INFO] (katana-sdk-python2) This package is up to date.
[INFO] (katana-sdk-python3) This package is up to date.
[INFO] (katapayadi) This package is up to date.
[INFO] (katastrophe) This package is up to date.
[INFO] (katcli) This package is up to date.
[INFO] (katcp) This package is up to date.
[INFO] (katcr) This package is up to date.
[INFO] (katdal) This package is up to date.
[ERROR] (kate) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kate-plugins) This package is up to date.
[INFO] (katello-cli) This package is up to date.
[ERROR] (katipo) This package does not have downloadable releases.
[INFO] (katnip) This package is up to date.
[INFO] (kato-base) This package is up to date.
[INFO] (kato-flaskappbuilder) This package is up to date.
[INFO] (kato-saas) This package is up to date.
[INFO] (katoadhocexpress) This package is up to date.
[INFO] (katpoint) This package is up to date.
[INFO] (katpy) This package is up to date.
[INFO] (katsdptelstate) This package is up to date.
[INFO] (kattcmd) This package is up to date.
[INFO] (katversion) This package is up to date.
[INFO] (katzj-test) This package is up to date.
[INFO] (kau-nested-list) This package is up to date.
[INFO] (kau3-tian2-iong7-ji7) This package is up to date.
[INFO] (kavahq-api) This package is up to date.
[INFO] (kavenegar) This package is up to date.
[INFO] (kaviar) This package is up to date.
[INFO] (kawaii) This package is up to date.
[INFO] (kawasemi) This package is up to date.
[INFO] (kayako) This package is up to date.
[INFO] (kaybee) This package is up to date.
[INFO] (kaybee-bulma) This package is up to date.
[INFO] (kaylee) This package is up to date.
[INFO] (kayleevc) This package is up to date.
[INFO] (kayobe) This package is up to date.
[INFO] (kayodeadechinan) This package is up to date.
[INFO] (kayvee) This package is up to date.
[INFO] (kazoo) This package is up to date.
[INFO] (kazoo-api) This package is up to date.
[INFO] (kazoo-eventlet-handler) This package is up to date.
[INFO] (kazoo-sasl) This package is up to date.
[INFO] (kazoo-sdk) This package is up to date.
[INFO] (kazoo-yandex) This package is up to date.
[INFO] (kazookid) This package is up to date.
[INFO] (kazurator) This package is up to date.
[INFO] (kazy) This package is up to date.
[INFO] (kb) This package is up to date.
[INFO] (kb-transaction) This package is up to date.
[INFO] (kbbi) This package is up to date.
[ERROR] (kbdgen) This package does not have downloadable releases.
[INFO] (kbinterface) This package is up to date.
[INFO] (kbinxml) This package is up to date.
[INFO] (kbkdna) This package is up to date.
[INFO] (kc-sanitize) This package is up to date.
[INFO] (kcardum) This package is up to date.
[INFO] (kcat) This package is up to date.
[INFO] (kcbo) This package is up to date.
[INFO] (kcc) This package is up to date.
[INFO] (kcem) This package is up to date.
[INFO] (kcfconvoy) This package is up to date.
[INFO] (kck) This package is up to date.
[INFO] (kclboot) This package is up to date.
[INFO] (kcli) This package is up to date.
[INFO] (kclient) This package is up to date.
[INFO] (kclist) This package is up to date.
[INFO] (kclpy) This package is up to date.
[INFO] (kcm) This package is up to date.
[INFO] (kcm-nester) This package is up to date.
[INFO] (kcmapp) This package is up to date.
[INFO] (kcommonmodule) This package is up to date.
[INFO] (kconfiglib) Data has been updated for this package.
[ERROR] (kcorrect-python) Could not extract data from this package. See below for details.
Execution of /usr/bin/python3.5 -m pypicontents.wrapper /tmp/pypic-extract/kcorrect-python/kcorrect_python-2017.07.05/setup.py failed with the following messages:
[stderr] Traceback (most recent call last):
  File "/tmp/pypic-extract/kcorrect-python/kcorrect_python-2017.07.05/setup.py", line 9, in <module>
    kcorrect_dir = os.environ['KCORRECT_DIR']
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'KCORRECT_DIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/wrapper.py", line 64, in <module>
    exec(compile(s(_sfile.read()), setuppath, 'exec'), env)
  File "/tmp/pypic-extract/kcorrect-python/kcorrect_python-2017.07.05/setup.py", line 11, in <module>
    raise SystemExit('KCORRECT_DIR must be set')
SystemExit: KCORRECT_DIR must be set
Execution of /usr/bin/python2.7 -m pypicontents.wrapper /tmp/pypic-extract/kcorrect-python/kcorrect_python-2017.07.05/setup.py failed with the following messages:
[stderr] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pypicontents/wrapper.py", line 64, in <module>
    exec(compile(s(_sfile.read()), setuppath, 'exec'), env)
  File "/tmp/pypic-extract/kcorrect-python/kcorrect_python-2017.07.05/setup.py", line 11, in <module>
    raise SystemExit('KCORRECT_DIR must be set')
SystemExit: KCORRECT_DIR must be setTraceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 89, in execute_wrapper
    return json.loads(store.read()), ''
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 89, in execute_wrapper
    return json.loads(store.read()), ''
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[INFO] (kcp-net) This package is up to date.
[INFO] (kcp-wrapper) This package is up to date.
[INFO] (kcrw-nprapi) This package is up to date.
[INFO] (kcshell) This package is up to date.
[INFO] (kd100) This package is up to date.
[INFO] (kdb) This package is up to date.
[INFO] (kdbq-kernel) This package is up to date.
[INFO] (kdcld) This package is up to date.
[INFO] (kdcount) This package is up to date.
[INFO] (kdcproxy) This package is up to date.
[INFO] (kddcup2015-cli) This package is up to date.
[INFO] (kddg) This package is up to date.
[ERROR] (kdenlive-tools) This package does not have downloadable releases.
[INFO] (kdense) This package is up to date.
[INFO] (kdepy) This package is up to date.
[INFO] (kdf) This package is up to date.
[ERROR] (kdic-project) This package does not have downloadable releases.
[INFO] (kdjflsdjflksdjf) This package is up to date.
[INFO] (kdm-snakemake-helpers) This package is up to date.
[INFO] (kdniao) This package is up to date.
[INFO] (kdotp-symmetry) This package is up to date.
[INFO] (kdquery) This package is up to date.
[INFO] (kdr) This package is up to date.
[INFO] (kdsearch) This package is up to date.
[INFO] (kdtree) This package is up to date.
[INFO] (kdu-jp2) This package is up to date.
[ERROR] (kdv) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (kdvs) This package is up to date.
[INFO] (kea) This package is up to date.
[INFO] (kea-call-center) This package is up to date.
[INFO] (kea-exporter) This package is up to date.
[INFO] (kea2) This package is up to date.
[INFO] (keacloud-call-center) This package is up to date.
[INFO] (keas-build) This package is up to date.
[INFO] (keas-googlemap) This package is up to date.
[INFO] (keas-kmi) This package is up to date.
[INFO] (keas-pbpersist) This package is up to date.
[INFO] (keas-pbstate) This package is up to date.
[INFO] (keas-profile) This package is up to date.
[INFO] (keas-unit) This package is up to date.
[ERROR] (kebab) This package does not have downloadable releases.
[ERROR] (kebap) This package does not have downloadable releases.
[INFO] (kebechet) This package is up to date.
[INFO] (keccak-hash) This package is up to date.
[INFO] (kecpkg-tools) This package is up to date.
[INFO] (kedo-ddtrace) This package is up to date.
[INFO] (kedo-facebook-sdk) This package is up to date.
[INFO] (kedo-kazoo) This package is up to date.
[ERROR] (kedo-oauthlib) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (kedo-pex) This package is up to date.
[ERROR] (kedpm) This package does not have downloadable releases.
[INFO] (kedsort) This package is up to date.
[INFO] (kedsort-cli) This package is up to date.
[ERROR] (kee) This package does not have downloadable releases.
[INFO] (keel) This package is up to date.
[INFO] (keen) This package is up to date.
[INFO] (keen-csv) This package is up to date.
[INFO] (keen-softlayer) This package is up to date.
[INFO] (keenmqtt) This package is up to date.
[INFO] (keep) This package is up to date.
[INFO] (keep-iam-creds-fresh) This package is up to date.
[INFO] (keep-password) This package is up to date.
[INFO] (keep-passwords) This package is up to date.
[INFO] (keep-running) This package is up to date.
[INFO] (keepaapi) This package is up to date.
[INFO] (keepalive) This package is up to date.
[INFO] (keepaneyeon) This package is up to date.
[INFO] (keepass) This package is up to date.
[INFO] (keepass-cli) This package is up to date.
[INFO] (keepass-http) This package is up to date.
[INFO] (keepassc) This package is up to date.
[INFO] (keepassdb) This package is up to date.
[INFO] (keepasshttplib) This package is up to date.
[INFO] (keepassx) This package is up to date.
[INFO] (keepboo-bookmarksparser) This package is up to date.
[INFO] (keepboo-opengraph) This package is up to date.
[INFO] (keepbot-asle) This package is up to date.
[INFO] (keepcli) This package is up to date.
[INFO] (keeper) This package is up to date.
[INFO] (keeper-contracts) This package is up to date.
[INFO] (keepercommander) This package is up to date.
[INFO] (keepify-py) This package is up to date.
[INFO] (keepitfresh) This package is up to date.
[INFO] (keepkey) This package is up to date.
[INFO] (keepkey-agent) This package is up to date.
[INFO] (keepluggable) This package is up to date.
[INFO] (keepmenu) This package is up to date.
[INFO] (keepmeposted) This package is up to date.
[INFO] (keepnote) This package is up to date.
[INFO] (keepserver) This package is up to date.
[INFO] (keepstart) This package is up to date.
[ERROR] (keepup) This package does not have downloadable releases.
[INFO] (kees) This package is up to date.
[INFO] (keg) This package is up to date.
[INFO] (keg-mail) This package is up to date.
[WARNING] 
[WARNING] Processing has taken more than 2100 seconds. Interrupting.
[WARNING] Processing will continue in next iteration.
[WARNING] 
[INFO] 
[INFO] 
[INFO] Total packages: 2019
[INFO]     Packages processed: 460
[INFO]         Packages updated: 1
[INFO]         Packages up-to-date: 423
[INFO]         Packages without response: 10
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 22
[INFO]         Packages with data errors: 4
[INFO]     Packages not processed: 1559
[INFO] 
[INFO] 
[INFO] Ending execution.
