[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[INFO] (q) This package is up to date.
[INFO] (q-a-dependencies) This package is up to date.
[INFO] (q-ctrl) This package is up to date.
[INFO] (q-stdev) This package is up to date.
[INFO] (q2) This package is up to date.
[INFO] (q2-itsxpress) This package is up to date.
[INFO] (q2k) This package is up to date.
[INFO] (q3huff) This package is up to date.
[ERROR] (qa) This package does not have downloadable releases.
[INFO] (qa-tests) This package is up to date.
[INFO] (qaamus) This package is up to date.
[INFO] (qabal) This package is up to date.
[INFO] (qacode) This package is up to date.
[INFO] (qad) This package is up to date.
[INFO] (qal) This package is up to date.
[ERROR] (qalab) This package does not have downloadable releases.
[INFO] (qalaboratory) This package is up to date.
[INFO] (qalculator) This package is up to date.
[INFO] (qalsadi) This package is up to date.
[INFO] (qam) This package is up to date.
[INFO] (qamasu) This package is up to date.
[INFO] (qanat) This package is up to date.
[INFO] (qanda) This package is up to date.
[INFO] (qap) This package is up to date.
[INFO] (qapla) This package is up to date.
[INFO] (qapplicationtemplate) This package is up to date.
[ERROR] (qarbon) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://pypi.python.org/packages/source/d/qarbon"
[INFO] (qarg) This package is up to date.
[INFO] (qarnot) This package is up to date.
[INFO] (qash) This package is up to date.
[INFO] (qasino-client) This package is up to date.
[ERROR] (qasm2error) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qasm2image) This package is up to date.
[INFO] (qasymphony-qtest-library) This package is up to date.
[INFO] (qatestlink) This package is up to date.
[INFO] (qautils) This package is up to date.
[INFO] (qav) This package is up to date.
[INFO] (qball) This package is up to date.
[ERROR] (qbar) This package does not have downloadable releases.
[INFO] (qbatch) This package is up to date.
[INFO] (qbcodespecs) This package is up to date.
[INFO] (qbertconfig) This package is up to date.
[INFO] (qbirthday) This package is up to date.
[INFO] (qbit) This package is up to date.
[INFO] (qbittorrent) This package is up to date.
[INFO] (qborg) This package is up to date.
[INFO] (qbroker) This package is up to date.
[INFO] (qbuf) This package is up to date.
[INFO] (qbuilder) This package is up to date.
[INFO] (qbx) This package is up to date.
[INFO] (qc) This package is up to date.
[INFO] (qc-statusmessage) This package is up to date.
[INFO] (qcache) This package is up to date.
[INFO] (qcache-client) This package is up to date.
[INFO] (qcandyui) This package is up to date.
[INFO] (qcat-basic) Data has been updated for this package.
[INFO] (qcbacktester) This package is up to date.
[INFO] (qccodar) This package is up to date.
[INFO] (qcd) This package is up to date.
[INFO] (qcengine) This package is up to date.
[INFO] (qcfoptions) This package is up to date.
[INFO] (qche) This package is up to date.
[INFO] (qchviewer) This package is up to date.
[INFO] (qcl) This package is up to date.
[INFO] (qcli) This package is up to date.
[INFO] (qcloud) This package is up to date.
[INFO] (qcloud-ccs) This package is up to date.
[INFO] (qcloud-cos) This package is up to date.
[INFO] (qcloud-cos-py3) This package is up to date.
[INFO] (qcloud-cos-v3) This package is up to date.
[INFO] (qcloud-cos-v4) This package is up to date.
[INFO] (qcloud-image) This package is up to date.
[INFO] (qcloud-video) This package is up to date.
[INFO] (qcloudapi) This package is up to date.
[INFO] (qcloudapi-sdk-python) This package is up to date.
[INFO] (qcloudapi3) This package is up to date.
[INFO] (qcloudchameleon) This package is up to date.
[INFO] (qcloudcli) This package is up to date.
[INFO] (qcloudsms-py) This package is up to date.
[INFO] (qcmaskingcode) This package is up to date.
[INFO] (qcodes) This package is up to date.
[INFO] (qcon) This package is up to date.
[INFO] (qconcurrency) This package is up to date.
[INFO] (qcore) This package is up to date.
[INFO] (qcore-nocython) This package is up to date.
[INFO] (qcos) This package is up to date.
[INFO] (qcos-cli) This package is up to date.
[INFO] (qcqp) This package is up to date.
[INFO] (qcrash) This package is up to date.
[INFO] (qcri) This package is up to date.
[INFO] (qcsv) This package is up to date.
[ERROR] (qct) Could not extract data from this package. See below for details.
Could not extract tarball. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 1631, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1607, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.5/tarfile.py", line 2281, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.5/tarfile.py", line 1082, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<h')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 131, in get_tar_topdir
    with closing(compressed(tarpath, tarmode)) as tar:
  File "/usr/lib/python3.5/tarfile.py", line 1577, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1635, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

[INFO] (qctoolkit) This package is up to date.
[INFO] (qctrl) This package is up to date.
[INFO] (qcustomplot) This package is up to date.
[INFO] (qcware) This package is up to date.
[INFO] (qd) This package is up to date.
[INFO] (qdarkgraystyle) This package is up to date.
[INFO] (qdarkstyle) This package is up to date.
[INFO] (qdatastream) This package is up to date.
[INFO] (qdatum) This package is up to date.
[INFO] (qdb) This package is up to date.
[INFO] (qdbd) This package is up to date.
[INFO] (qddate) This package is up to date.
[INFO] (qdds) This package is up to date.
[INFO] (qdict) This package is up to date.
[INFO] (qdj) This package is up to date.
[INFO] (qdns) This package is up to date.
[INFO] (qdo) This package is up to date.
[INFO] (qdrouter-jinja2) This package is up to date.
[INFO] (qds-app) This package is up to date.
[INFO] (qds-sdk) This package is up to date.
[INFO] (qdssdk) This package is up to date.
[INFO] (qdudomportal) This package is up to date.
[INFO] (qdune) This package is up to date.
[INFO] (qdupe) This package is up to date.
[INFO] (qdutaportal) This package is up to date.
[INFO] (qdyn) This package is up to date.
[INFO] (qe-tools) This package is up to date.
[ERROR] (qecalc) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://danse.cacr.caltech.edu/packages/dev_danse_us/"
[ERROR] (qed) This package does not have downloadable releases.
[INFO] (qed-seal) This package is up to date.
[INFO] (qef) This package is up to date.
[INFO] (qegraphmaker) This package is up to date.
[INFO] (qemu-affinity) This package is up to date.
[ERROR] (qemud) This package does not have downloadable releases.
[INFO] (qeschema) This package is up to date.
[INFO] (qet-tb-generator) This package is up to date.
[INFO] (qeutil) This package is up to date.
[INFO] (qeventlog) This package is up to date.
[ERROR] (qexpy) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (qextract) This package is up to date.
[INFO] (qface) This package is up to date.
[INFO] (qface-qtcpp) This package is up to date.
[INFO] (qface-qtqml) This package is up to date.
[INFO] (qface-qtro) This package is up to date.
[INFO] (qface-store) This package is up to date.
[INFO] (qfathom) This package is up to date.
[INFO] (qfilters) This package is up to date.
[INFO] (qflashlight) This package is up to date.
[INFO] (qfragment) This package is up to date.
[INFO] (qfreq) This package is up to date.
[INFO] (qfrm) This package is up to date.
[INFO] (qfx-scraper) This package is up to date.
[INFO] (qg-core) This package is up to date.
[INFO] (qg-db) This package is up to date.
[INFO] (qg-test) This package is up to date.
[INFO] (qg-utils) This package is up to date.
[INFO] (qg-web) This package is up to date.
[INFO] (qgdt) This package is up to date.
[INFO] (qgdt-cpu) This package is up to date.
[INFO] (qgen) This package is up to date.
[INFO] (qgeneration) This package is up to date.
[INFO] (qgis-plugins) This package is up to date.
[INFO] (qgis2to3) This package is up to date.
[INFO] (qgiscommons) This package is up to date.
[INFO] (qgispluginreleaser) This package is up to date.
[INFO] (qgl) This package is up to date.
[INFO] (qgmap) This package is up to date.
[INFO] (qgprofiler) This package is up to date.
[INFO] (qgrid) This package is up to date.
[INFO] (qgsctx) This package is up to date.
[INFO] (qha) This package is up to date.
[INFO] (qhangups) This package is up to date.
[INFO] (qhist) This package is up to date.
[INFO] (qhonuskan-votes) This package is up to date.
[INFO] (qhue) This package is up to date.
[INFO] (qi) This package is up to date.
[INFO] (qi-goban) This package is up to date.
[INFO] (qi-grsplitter) This package is up to date.
[INFO] (qi-jabberhelpdesk) This package is up to date.
[INFO] (qi-jwmedia) This package is up to date.
[INFO] (qi-livechat) This package is up to date.
[INFO] (qi-portlet-tagclouds) This package is up to date.
[INFO] (qi-xmpp-admin) This package is up to date.
[INFO] (qi-xmpp-botfarm) This package is up to date.
[INFO] (qi-xmpp-client) This package is up to date.
[INFO] (qibuild) This package is up to date.
[INFO] (qidicom) This package is up to date.
[INFO] (qifparse) This package is up to date.
[INFO] (qifparser) This package is up to date.
[INFO] (qifqif) This package is up to date.
[INFO] (qiidly) This package is up to date.
[INFO] (qiime) This package is up to date.
[ERROR] (qiime-2-ll-quick-viewer) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (qiime-default-reference) This package is up to date.
[INFO] (qiime-tools) This package is up to date.
[INFO] (qiita) This package is up to date.
[INFO] (qiita-api-wrapper) This package is up to date.
[INFO] (qiita-spots) This package is up to date.
[INFO] (qiita-v2) This package is up to date.
[INFO] (qiitap) This package is up to date.
[INFO] (qimage2ndarray) This package is up to date.
[INFO] (qimport) This package is up to date.
[INFO] (qinfer) This package is up to date.
[INFO] (qing) This package is up to date.
[INFO] (qing-framework) This package is up to date.
[INFO] (qingchat) This package is up to date.
[ERROR] (qingchat-server) This package does not have downloadable releases.
[INFO] (qingcloud-cli) This package is up to date.
[INFO] (qingcloud-init) This package is up to date.
[INFO] (qingcloud-sdk) This package is up to date.
[INFO] (qingcloudrc) This package is up to date.
[INFO] (qingfeng) This package is up to date.
[INFO] (qinghama) This package is up to date.
[INFO] (qingmi) This package is up to date.
[INFO] (qingstor) This package is up to date.
[INFO] (qingstor-sdk) This package is up to date.
[INFO] (qiniu) This package is up to date.
[INFO] (qiniu-cli) This package is up to date.
[INFO] (qiniu-lite) This package is up to date.
[INFO] (qiniu-storage) This package is up to date.
[INFO] (qiniu-upload) This package is up to date.
[INFO] (qiniu4blog) This package is up to date.
[INFO] (qiniu4blog-mk) This package is up to date.
[INFO] (qiniufoldersync) This package is up to date.
[INFO] (qiniufops) This package is up to date.
[INFO] (qiniufs) This package is up to date.
[INFO] (qiniumanager) This package is up to date.
[INFO] (qinxiaoutil) This package is up to date.
[INFO] (qip) This package is up to date.
[INFO] (qipipe) This package is up to date.
[ERROR] (qipp) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qiprofile-rest) This package is up to date.
[INFO] (qiprofile-rest-client) This package is up to date.
[INFO] (qipu) This package is up to date.
[INFO] (qipy) This package is up to date.
[INFO] (qiqi20160209) This package is up to date.
[INFO] (qirest) This package is up to date.
[INFO] (qirest-client) This package is up to date.
[INFO] (qiscus-sdk) This package is up to date.
[INFO] (qiscusapi) This package is up to date.
[INFO] (qiskit) This package is up to date.
[INFO] (qiskit-acqua) This package is up to date.
[INFO] (qiskit-acqua-chemistry) This package is up to date.
[INFO] (qiskit-addon-jku) Data has been updated for this package.
[INFO] (qiskit-aqua) This package is up to date.
[INFO] (qiskit-aqua-chemistry) This package is up to date.
[INFO] (qit) This package is up to date.
[ERROR] (qitensor) This package does not have downloadable releases.
[INFO] (qiu-nester) This package is up to date.
[INFO] (qiubai) This package is up to date.
[ERROR] (qiushi-mp4-download) This package does not have downloadable releases.
[INFO] (qiutil) This package is up to date.
[INFO] (qiuyuan) This package is up to date.
[ERROR] (qiwan) This package does not have downloadable releases.
[INFO] (qiwi-api) This package is up to date.
[INFO] (qiwiapi) This package is up to date.
[INFO] (qiwipy) This package is up to date.
[INFO] (qixingjiang) This package is up to date.
[INFO] (qixnat) This package is up to date.
[ERROR] (qiyi-utils) This package does not have downloadable releases.
[INFO] (qj) This package is up to date.
[INFO] (qjam) This package is up to date.
[INFO] (qjobs) This package is up to date.
[INFO] (qjson) This package is up to date.
[INFO] (qk) This package is up to date.
[ERROR] (qkdb) This package does not have downloadable releases.
[INFO] (qksh) This package is up to date.
[INFO] (ql-charon) This package is up to date.
[INFO] (ql-demo) This package is up to date.
[ERROR] (ql-pubsub) This package does not have downloadable releases.
[INFO] (qlab) This package is up to date.
[INFO] (qlcompiler) This package is up to date.
[INFO] (qlda) This package is up to date.
[INFO] (qlds-manager) This package is up to date.
[INFO] (qlearning) This package is up to date.
[INFO] (qled) This package is up to date.
[INFO] (qless-py) This package is up to date.
[INFO] (qless-util) This package is up to date.
[INFO] (qlik-script-tools) This package is up to date.
[INFO] (qlink) This package is up to date.
[INFO] (qllauncher) This package is up to date.
[ERROR] (qloggingdialog) This package does not have downloadable releases.
[INFO] (qlogtask) This package is up to date.
[INFO] (qlutils) This package is up to date.
[INFO] (qm) This package is up to date.
[INFO] (qm-scripts) This package is up to date.
[INFO] (qmachine) This package is up to date.
[INFO] (qmarkpg) This package is up to date.
[INFO] (qmath) This package is up to date.
[INFO] (qmc5883l) This package is up to date.
[ERROR] (qmenta) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qmenta-client) This package is up to date.
[INFO] (qmenta-sdk-lib) This package is up to date.
[INFO] (qmenuview) This package is up to date.
[INFO] (qmeq) This package is up to date.
[INFO] (qmesh) This package is up to date.
[INFO] (qmesh-cli) This package is up to date.
[INFO] (qmflows) This package is up to date.
[INFO] (qmi) This package is up to date.
[INFO] (qml) This package is up to date.
[INFO] (qmlt) This package is up to date.
[ERROR] (qmmmtools) This package does not have downloadable releases.
[INFO] (qmon) This package is up to date.
[INFO] (qmongohelper) This package is up to date.
[INFO] (qmonitor-client) This package is up to date.
[INFO] (qmorph) This package is up to date.
[INFO] (qmpy) This package is up to date.
[INFO] (qms) This package is up to date.
[INFO] (qmvpa) This package is up to date.
[INFO] (qmworks) This package is up to date.
[INFO] (qmxgraph) This package is up to date.
[INFO] (qn) This package is up to date.
[INFO] (qn2-sig) This package is up to date.
[INFO] (qnapstats) This package is up to date.
[ERROR] (qnester) This package does not have downloadable releases.
[INFO] (qnet) This package is up to date.
[INFO] (qnet-qsd) This package is up to date.
[INFO] (qng) This package is up to date.
[INFO] (qnpct) This package is up to date.
[INFO] (qnupload) This package is up to date.
[ERROR] (qombinatorics) This package does not have downloadable releases.
[INFO] (qonda) This package is up to date.
[INFO] (qonos) This package is up to date.
[INFO] (qoob) This package is up to date.
[INFO] (qooxdoocherrypyjsonrpc) This package is up to date.
[INFO] (qopen) This package is up to date.
[INFO] (qopenvpn) This package is up to date.
[INFO] (qordoba) This package is up to date.
[ERROR] (qp) This package does not have downloadable releases.
[INFO] (qpack) This package is up to date.
[INFO] (qpage) This package is up to date.
[INFO] (qpagent) This package is up to date.
[INFO] (qpass) This package is up to date.
[INFO] (qpformat) This package is up to date.
[INFO] (qpic) This package is up to date.
[INFO] (qpid-bow) This package is up to date.
[INFO] (qpid-python) This package is up to date.
[INFO] (qpid-qmf) This package is up to date.
[INFO] (qpid-tools) This package is up to date.
[INFO] (qpidpython) This package is up to date.
[INFO] (qpimage) This package is up to date.
[INFO] (qpipe) This package is up to date.
[INFO] (qplots) This package is up to date.
[INFO] (qpm) This package is up to date.
[INFO] (qpmg) This package is up to date.
[INFO] (qprocessing) This package is up to date.
[INFO] (qprompt) This package is up to date.
[INFO] (qprop) This package is up to date.
[INFO] (qps) This package is up to date.
[INFO] (qpsh) This package is up to date.
[INFO] (qpsolvers) This package is up to date.
[INFO] (qpsphere) This package is up to date.
[INFO] (qpth) This package is up to date.
[INFO] (qptomographer) This package is up to date.
[ERROR] (qpy) This package does not have downloadable releases.
[ERROR] (qpyprofiler) Could not extract data from this package. See below for details.
"http://www.digitalfox.org/projets/download/qPyProfiler.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

[INFO] (qpython) This package is up to date.
[INFO] (qpyutils) Data has been updated for this package.
[INFO] (qq) This package is up to date.
[INFO] (qqbot) This package is up to date.
[INFO] (qqhistorycut) This package is up to date.
[INFO] (qqlib) This package is up to date.
[INFO] (qqlogintool) This package is up to date.
[INFO] (qqpat) This package is up to date.
[INFO] (qqqfome) This package is up to date.
[INFO] (qqqq) This package is up to date.
[ERROR] (qqqstest) This package does not have downloadable releases.
[INFO] (qqsuperman) This package is up to date.
[INFO] (qquery) This package is up to date.
[INFO] (qquiz) This package is up to date.
[INFO] (qqweibo) This package is up to date.
[INFO] (qqwry) This package is up to date.
[INFO] (qqwry-py2) This package is up to date.
[INFO] (qqwry-py3) This package is up to date.
[INFO] (qr) This package is up to date.
[ERROR] (qr-code) This package does not have downloadable releases.
[INFO] (qr-codec) This package is up to date.
[INFO] (qr-io) This package is up to date.
[INFO] (qr2cnc) This package is up to date.
[INFO] (qr2scad) This package is up to date.
[INFO] (qr3) This package is up to date.
[INFO] (qr3d) This package is up to date.
[ERROR] (qradar4py) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qradial-menu) This package is up to date.
[INFO] (qrangeslider) This package is up to date.
[INFO] (qraphql-py) This package is up to date.
[INFO] (qrc) This package is up to date.
[INFO] (qrc-build) This package is up to date.
[INFO] (qrc-pathlib) This package is up to date.
[INFO] (qrcgen) This package is up to date.
[INFO] (qrcode) This package is up to date.
[INFO] (qrcode-converter) This package is up to date.
[INFO] (qrcode-song) This package is up to date.
[INFO] (qrcode-terminal) This package is up to date.
[INFO] (qrcodegen) This package is up to date.
[INFO] (qrdecode) This package is up to date.
[INFO] (qrdecodexy) This package is up to date.
[INFO] (qredis) This package is up to date.
[INFO] (qreg) This package is up to date.
[INFO] (qregexeditor) This package is up to date.
[INFO] (qrencode) This package is up to date.
[INFO] (qrep) This package is up to date.
[INFO] (qrequest) This package is up to date.
[INFO] (qreu) This package is up to date.
[INFO] (qri) This package is up to date.
[INFO] (qri-py) This package is up to date.
[INFO] (qrisk) This package is up to date.
[INFO] (qrkit) This package is up to date.
[INFO] (qrl) Data has been updated for this package.
[INFO] (qrmr) This package is up to date.
[INFO] (qrnn) This package is up to date.
[INFO] (qrnr) This package is up to date.
[INFO] (qroundprogressbar) This package is up to date.
[INFO] (qrpc) This package is up to date.
[INFO] (qrplatba) This package is up to date.
[INFO] (qrplatba-fpdf) This package is up to date.
[INFO] (qrtools) This package is up to date.
[INFO] (qrtray) This package is up to date.
[INFO] (qrypto) This package is up to date.
[INFO] (qs) This package is up to date.
[ERROR] (qs-nester) This package does not have downloadable releases.
[INFO] (qs-params) This package is up to date.
[ERROR] (qs-vod-metadata) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "https://bitbucket.org/quicksisver_dev_phase_1/metadata_gen/src"
[INFO] (qsar-ssd-toolbox) This package is up to date.
[INFO] (qscan) This package is up to date.
[INFO] (qscintilla) This package is up to date.
[INFO] (qscollect) This package is up to date.
[INFO] (qscollect-withings) This package is up to date.
[INFO] (qsctl) This package is up to date.
[INFO] (qserious) This package is up to date.
[INFO] (qserve) This package is up to date.
[INFO] (qsgen) This package is up to date.
[INFO] (qsignal) This package is up to date.
[INFO] (qslaunch) This package is up to date.
[INFO] (qsnark-python-sdk) This package is up to date.
[INFO] (qson) This package is up to date.
[INFO] (qspectrumanalyzer) This package is up to date.
[INFO] (qspin) This package is up to date.
[INFO] (qspypy) This package is up to date.
[INFO] (qsqla) This package is up to date.
[INFO] (qss-debugger) This package is up to date.
[INFO] (qstat) This package is up to date.
[INFO] (qstatistic) This package is up to date.
[INFO] (qstem-ase) This package is up to date.
[INFO] (qstest) This package is up to date.
[INFO] (qstk) This package is up to date.
[INFO] (qstring) This package is up to date.
[INFO] (qstylizer) This package is up to date.
[INFO] (qsupervisorcontrol) This package is up to date.
[INFO] (qsymm) This package is up to date.
[ERROR] (qt) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qt-backport) This package is up to date.
[INFO] (qt-binder) This package is up to date.
[ERROR] (qt-cef) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (qt-dataflow) This package does not have downloadable releases.
[INFO] (qt-graph-helpers) This package is up to date.
[INFO] (qt-ledwidget) This package is up to date.
[INFO] (qt-multiprocessing) This package is up to date.
[INFO] (qt-nester) This package is up to date.
[INFO] (qt-object-viewer) This package is up to date.
[INFO] (qt-py) This package is up to date.
[INFO] (qt-style-sheet-inspector) This package is up to date.
[INFO] (qt-widgetstyler) This package is up to date.
[INFO] (qt4-gengui) This package is up to date.
[INFO] (qt4imagelabel) This package is up to date.
[INFO] (qt4reactor) This package is up to date.
[INFO] (qt5-cef) This package is up to date.
[INFO] (qt5-py) This package is up to date.
[INFO] (qt5reactor) This package is up to date.
[INFO] (qt5reactor-fork) This package is up to date.
[INFO] (qtaf) This package is up to date.
[INFO] (qtalchemy) This package is up to date.
[INFO] (qtargselector) This package is up to date.
[INFO] (qtarmsim) This package is up to date.
[INFO] (qtask) This package is up to date.
[INFO] (qtaui) This package is up to date.
[INFO] (qtawesome) This package is up to date.
[INFO] (qtbe) This package is up to date.
[INFO] (qtbot) This package is up to date.
[INFO] (qtconsole) This package is up to date.
[INFO] (qtdigest) This package is up to date.
[INFO] (qtdjango) This package is up to date.
[ERROR] (qte) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://bitbucket.org/aquavitae/qte/downloads"
[ERROR] (qtest) This package does not have downloadable releases.
[INFO] (qtfaststart) This package is up to date.
[INFO] (qtgui) This package is up to date.
[INFO] (qth) This package is up to date.
[INFO] (qth-alias) This package is up to date.
[INFO] (qth-darksky) This package is up to date.
[INFO] (qth-gc) This package is up to date.
[INFO] (qth-ls) This package is up to date.
[INFO] (qth-national-rail) This package is up to date.
[INFO] (qth-panasonic-viera) This package is up to date.
[INFO] (qth-postgres-log) This package is up to date.
[INFO] (qth-registrar) This package is up to date.
[INFO] (qth-yarp) This package is up to date.
[INFO] (qthread) This package is up to date.
[INFO] (qtickle) This package is up to date.
[INFO] (qtico) This package is up to date.
[INFO] (qtile) This package is up to date.
[INFO] (qtile-plasma) This package is up to date.
[INFO] (qtilities) This package is up to date.
[INFO] (qtim-tools) This package is up to date.
[INFO] (qtimer) This package is up to date.
[INFO] (qtip) This package is up to date.
[ERROR] (qtip-api) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (qtip-cli) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (qtipy) This package is up to date.
[INFO] (qtk) This package is up to date.
[INFO] (qtlsearch) This package is up to date.
[INFO] (qtm) This package is up to date.
[INFO] (qtmacs) This package is up to date.
[INFO] (qtmodern) This package is up to date.
[INFO] (qtmud) This package is up to date.
[INFO] (qtnanester) This package is up to date.
[INFO] (qtodotxt) This package is up to date.
[INFO] (qtodotxt2) This package is up to date.
[INFO] (qtoml) This package is up to date.
[INFO] (qtools) This package is up to date.
[INFO] (qtop) This package is up to date.
[INFO] (qtopic) This package is up to date.
[INFO] (qtornado) This package is up to date.
[INFO] (qtpad) This package is up to date.
[INFO] (qtpandas) This package is up to date.
[INFO] (qtpaws) This package is up to date.
[INFO] (qtpdfprinter) This package is up to date.
[INFO] (qtplot) This package is up to date.
[INFO] (qtpy) This package is up to date.
[INFO] (qtpyconvert) This package is up to date.
[INFO] (qtpylib) This package is up to date.
[ERROR] (qtreactor) This package does not have downloadable releases.
[INFO] (qtrequests) This package is up to date.
[INFO] (qtrotate) This package is up to date.
[INFO] (qtsix) This package is up to date.
[INFO] (qtsnbl) This package is up to date.
[INFO] (qtstuff) This package is up to date.
[INFO] (qtstyles) This package is up to date.
[INFO] (qttest) This package is up to date.
[INFO] (qtum) This package is up to date.
[INFO] (qtumblr) This package is up to date.
[INFO] (qturtle) This package is up to date.
[INFO] (qtutils) This package is up to date.
[INFO] (qtviews) This package is up to date.
[INFO] (qtwirl) This package is up to date.
[INFO] (qtx) This package is up to date.
[INFO] (qtxmldom) This package is up to date.
[INFO] (qu) This package is up to date.
[INFO] (quack) This package is up to date.
[INFO] (quad-form-ratio) This package is up to date.
[INFO] (quade) This package is up to date.
[INFO] (quadkey) This package is up to date.
[INFO] (quadprog) This package is up to date.
[INFO] (quadpy) This package is up to date.
[INFO] (quadrant) This package is up to date.
[INFO] (quadratic) This package is up to date.
[INFO] (quadratum) This package is up to date.
[INFO] (quadriga) This package is up to date.
[INFO] (quadriga-bot) This package is up to date.
[INFO] (quadrigacx) This package is up to date.
[INFO] (quadruped) This package is up to date.
[INFO] (quadtree) This package is up to date.
[INFO] (quadwi) This package is up to date.
[INFO] (quaec) This package is up to date.
[INFO] (quaidan) This package is up to date.
[INFO] (quail) This package is up to date.
[ERROR] (quailbox) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (quaive-app-taxonomy) This package is up to date.
[INFO] (quaive-resources-ploneintranet) This package is up to date.
[INFO] (quakecl) This package is up to date.
[INFO] (quakefeeds) This package is up to date.
[INFO] (qualdocs) This package is up to date.
[INFO] (quali-testing-helpers) This package is up to date.
[INFO] (qualicscli) This package is up to date.
[WARNING] 
[WARNING] Processing has taken more than 2100 seconds. Interrupting.
[WARNING] Processing will continue in next iteration.
[WARNING] 
[INFO] 
[INFO] 
[INFO] Total packages: 1039
[INFO]     Packages processed: 565
[INFO]         Packages updated: 4
[INFO]         Packages up-to-date: 520
[INFO]         Packages without response: 11
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 24
[INFO]         Packages with data errors: 6
[INFO]     Packages not processed: 474
[INFO] 
[INFO] 
[INFO] Ending execution.
